"""add phone number

Revision ID: d474dfd41be5
Revises: acdb4b0be396
Create Date: 2022-05-17 12:57:20.569784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd474dfd41be5'
down_revision = 'acdb4b0be396'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users',sa.Column('phone_number',sa.String()))
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users','phone_number')
    pass
    # ### end Alembic commands ###
